### ISSUE TITLE
Removing DUD can remove the correct word.

### ISSUE THREAD

**Issue by DamourJustin** [Josh1147582/fallout-terminal-clone#4] opened 2016-09-30 23:04 UTC
While playing the correct word was removed after i removed a few duds:

![falloutterminalbroken](https://cloud.githubusercontent.com/assets/16315251/19009111/8bd3bdf8-873e-11e6-97fd-3b4f74349240.png)

Could be fixed by comparing the correct string and the selected string with `strcmp()`

**Comment by jibby0** [comment] 2016-09-30 23:59
Should be fixed in https://github.com/Josh1147582/fallout-terminal-clone/commit/39c9b6f7d4ac3bf17c92cd9f9ffffd775510279f . The full word was never read, meaning all words were recognized as duds.

Please reopen if the issue is still experienced.

**Closed as completed by jibby0** 2016-09-30 23:59 UTC
